### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by at00976** [stringlytyped/cloudnine#11]

**Comment by stringlytyped** [comment]
I have put together a mockup for the playlists page:

![cloudnine mockup](https://user-images.githubusercontent.com/1239396/80913832-827e6900-8d3f-11ea-8478-663d2dcb2c71.png)

If people could start implementing some of the individual components in the mockup, that would be great. To that end, I have put together a [UI Tutorial](https://github.com/stringlytyped/cloudnine/wiki/UI-Tutorial) that walks you through the process of creating the mood rating buttons.

I realize that some team members may not be very comfortable with CSS, but I am available to provide help where needed.

(I have also added some basic styles and removed unnecessary dependencies such as bootstrap on the `enhancement/11` branch. This does mean that things look pretty ugly at the moment, but this will improve as more of the UI is implemented.)
