### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by adriancttnc** [stringlytyped/cloudnine#3]

**Comment by adriancttnc** [comment]
Had an attempt, but was unhappy with the result. Saved the 'failed' attempt and started from scratch.

**Comment by adriancttnc** [comment]
18/03/2020 - When trying to run rails server got an error saying "Your yarn packages are out of date". Ran "yarn install --check-files" and fixed the issue.

**Comment by adriancttnc** [comment]
24/03/2020 - My first attempt at creating the authentication system was not looking that great, so I saved the files into a folder and planning to start from scratch.

**Comment by adriancttnc** [comment]
25/03/2020 - Started the project from scratch:
- cloned 
- ran "yarn install --check-files"
- started building on the app and created a welcome dashboard with a navbar
- encountered issues with the navbar dropdown menus and searched on about 10 forums until I (hopefully) have found a fix.

**Comment by adriancttnc** [comment]
27/03/2020 - Issue should now be almost done, although there are two problems encountered:
1) after a lot of struggle with the dropdown menus and some workarounds, I have managed to make them work, but they work only from the homepage.
2) CanCanCan gem, which restricts what a user can see/manage seems to be denying access to any role (user or admin). Need to investigate the issue. Have disabled this option for now.

**Comment by adriancttnc** [comment]
Following this tutorial : https://www.nopio.com/blog/authentication-authorization-rails/  for my attempt at the authentication system I have introduced three new gems into the application:
Devise, CanCanCan and Rolify:

- Devise is used as a flexible authentication solution which comes with multiple modules.

- Rolify is used to create and assign roles to users, which helps to differentiate between each separate user that have access to their own playlists only and users with administrative role that have access to all the playlists on the database. This gem is only used for creating and assigning roles.

- CanCanCan works with Rolify to restrict access to resources based on user's role. 

The development started with cloning the application then creating a homepage and by adding bootstrap and styles( navbar ).
After that I have then created a database with a table called playlists that stores the playlists and their rating, for now. This will be further developed at a later point in the project. The table contains, for now, two columns: Name (string) and rating ( float).
Links to the playlists table have been created with a few buttons and menus.
During this process I have encountered multiple issues with the dropdown menus as they would work only from the homepage. The pages could be accessed and used by navigating to the URL of that page.
After a temporarily work-around has been found for the drop down menus issue I proceeded to integrate the authentication system and the gems specified earlier.

Firstly I have installed Devise and added bootstrap to it, created a Users table (email and password only ) and linked it to the navbar. At first all the buttons would be visible (log in, sign up, log out, edit), but soon after implementing them I have set it up so that it only shows relevant buttons (sign in and sign up ) when not in a session and (edit and log out) when in an active session.

After these changes I have added username and user id to the User table so that playlists could be assigned to specific users only.

After making sure that a logged-in user can successfully create a playlist and that the playlist is successfully assigned to them, I have started working with the Rolify gem to add a User and an Admin role.

Modified seeds.rb to automatically seed the database with two users with different roles and with some playlists assigned to each of them.

On my attempt to setup CanCanCan and introduce abilities to the application I have stumbled over some issues with granting and restricting access to resources, which is still to be investigated.

**Comment by stringlytyped** [comment]
The default database authentication has now been replaced with a Spotify OAuth flow. To accomplish this, I have used the OmniAuth Spotify provider.

Additionally, I have reviewed the Devise configuration, making changes where appropriate and cleaning up some minor things.
